version: "3.0"
services:
  cleaner:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "cleaner"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      UPPER_THRESHOLD: 1000
      LOWER_THRESHOLD: -10
      RATE_OF_CHANGE_UPPER_THRESHOLD: 20
      RATE_OF_CHANGE_LOWER_THRESHOLD: -10
      OUTLIER_POLICY: "keep"
      INPUT_LABEL: "temperature"
    ports:
      - 80:80
